FROM registry.docker-cn.com/library/centos:latest
MAINTAINER Leon "test@weippt.com"
ENV REFRESHED_AT 2017-07-15
RUN yum -y install ruby rubygems rubygem-rake
RUN gem install --no-rdoc --no-ri rspec ci_reporter_rspec
